# Generated by Django 5.2.7 on 2025-10-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
