# Generated by Django 5.2.7 on 2025-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmain', '0002_rename_creted_at_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/gmain/'),
        ),
    ]
