# Generated by Django 5.2.7 on 2025-10-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmain', '0004_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/gmain/'),
        ),
    ]
