# Generated by Django 5.2.7 on 2025-10-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='addres1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='addres2',
            new_name='address2',
        ),
    ]
